### ISSUE TITLE
Hotspot analysis doesn't work after merging two Git repositories.

### ISSUE THREAD

**Issue by mhenrichsen** [smontanari/code-forensics#5] opened 2017-07-17 07:24 UTC
Hi @smontanari,

I've tried [this](https://stackoverflow.com/questions/13040958/merge-two-git-repositories-without-breaking-file-history) method to merge two repositories without messing with the history.

It seems to work fine, but when I run the hotspot analysis, there is no hotspots - all dots have the same color.

[Here is a picture](http://imgur.com/a/mEzmZ). 

Any ideas?

**Comment by smontanari** [comment] 2017-07-21 03:22
The symptom seems to be that your analysis results do not contain any complexity and/or lines of code metrics (depending on what diagram you're trying to visualise). It could be just a matter of configuring code-forensics the right way. If your code is in an open repo and you let me know which one I can give it a quick try and let you know

**Comment by dlehammer** [comment] 2017-10-13 10:50
The symptom described by @mhenrichsen seems to match my experience with `git subtree`.
I've also attempted to combine multiple git repositories into a single repository with each repository represented by a sub-directory, in-order to perform code-forensic on the full code-base.
I've created an example repo [here](https://github.com/dlehammer/code-forensics_git_subtree_issue-5).
The repo was created as follows (using Git v2.14.2):
```
$ mkdir code-forensics_git_subtree_issue-5 && cd code-forensics_git_subtree_issue-5

code-forensics_git_subtree_issue-5$ git init

code-forensics_git_subtree_issue-5$ echo "Workaround for fatal: /usr/lib/git-core/git-subtree cannot be used without a working tree." > dummy.txt

code-forensics_git_subtree_issue-5$ git add .

code-forensics_git_subtree_issue-5$ git commit --message="Workaround for fatal: /usr/lib/git-core/git-subtree cannot be used without a working tree."

code-forensics_git_subtree_issue-5$ git subtree add --prefix=grails-cache https://github.com/grails-plugins/grails-cache.git master

code-forensics_git_subtree_issue-5$ git subtree add --prefix=grails-quartz https://github.com/grails-plugins/grails-quartz.git master
```
Executing `git log` results in a promising result, my 3 commits + the full history
![code-forensics_git_subtree_issue-5_git_log](https://user-images.githubusercontent.com/17439718/31542506-94187280-b012-11e7-847a-59f784b93895.png)

Unfortunately `$ gulp hotspot-analysis --dateFrom=2007-05-07` doesn't provide the expected result.
![code-forensics_git_subtree_issue-5_hotspot_analysis](https://user-images.githubusercontent.com/17439718/31542557-c70a7b52-b012-11e7-80fe-1e4d5442ffe5.png)

Ie. it seems the number of commits are equal across the repo, how can that be... A visual representation gives a clue.
![code-forensics_git_subtree_issue-5_visual_git_log](https://user-images.githubusercontent.com/17439718/31542608-f86d541c-b012-11e7-8fb3-0846d1f594f9.png)

Hmm, further probing gives provide the following clue for a file with 100+ commits in the original repository.
![code-forensics_git_subtree_issue-5_visual_git_log_for_file](https://user-images.githubusercontent.com/17439718/31542764-acfaa9f2-b013-11e7-8944-a11845dbc90d.png)

I've tried to research the underlying issue, ie. retrieving the full history via `git log`, [this](https://stackoverflow.com/questions/10918244/git-subtree-without-squash-view-log) is the most informative discussion I've found.

Conclusion; this seems to be a `git` issue.

**Comment by dlehammer** [comment] 2017-10-13 13:45
Hotspot analysis works as intended for a single git-repository, in this example [grails-quartz](https://github.com/grails-plugins/grails-quartz).
![screenshot from 2017-10-13 15-42-37](https://user-images.githubusercontent.com/17439718/31549034-2cd8df0e-b02d-11e7-860e-3f5e4ecfd4e9.png)

**Comment by dlehammer** [comment] 2017-10-17 15:29
I couldn't let this issue go, as additional digging revealed there's several approaches for merging git repositories into a single git repository in separate sub-directories without loosing file history. An as described below I'm suspecting there's an issue here and perhaps it's possibe to tease out a fix

I've tried several approaches, they all seem to produce full history for ```git log``` but the result is seemingly incompatible with ```code-forensics```, for example [git-merge-repos](https://github.com/robinst/git-merge-repos#preserve-history-for-paths), [git-stitch-repo](https://metacpan.org/pod/git-stitch-repo), [How do you merge two Git repositories?](https://stackoverflow.com/a/21495718) [etc.](https://www.google.com/search?q=git+merge+repository+into+subdirectory).

Common for the above approaches is that ```code-forensics``` doesn't produce "Revision churn level" above 1 and the log output changes when run on merged repositories, I've uploaded an ```git-merge-repos``` example [here](https://github.com/dlehammer/code-forensics_git_merge-repos_issue-5).

When executing ```code-forensics``` on a single git repository as described in above [comment](https://github.com/smontanari/code-forensics/issues/5#issuecomment-336456797).
The following bolded line *is* present in the log.

> ...
> Starting 'vcs-log-dump'...
> **Fetching git log from 2015-01-01 to 2017-10-17**
> ...

When executing ```code-forensics``` on a merged git repository, [example](https://github.com/dlehammer/code-forensics_git_merge-repos_issue-5), the bolded line above is *omitted*!
And instead the following bolded line is present in the log.

> ...
> Starting 'hotspot-analysis'...
> **Can't determine weight of collection. Assigning a value of 0 to every item.**
> ...

Regardless, the full file history seems to present as far as ```git``` is concerned

![screenshot from 2017-10-17 15-58-37](https://user-images.githubusercontent.com/17439718/31673806-72f88ba2-b360-11e7-8c83-1dd8548652f2.png)

Utilizing ```git log``` on the same example as [above](https://github.com/smontanari/code-forensics/issues/5#issuecomment-336418929), provides the full file history as expected.

![screenshot from 2017-10-17 15-59-44](https://user-images.githubusercontent.com/17439718/31673826-7b028154-b360-11e7-9e8a-68531b7d1ae2.png)

I've tried digging around in the source for ```code-forensics```, and found the following in [git_adapter.js](https://github.com/smontanari/code-forensics/blob/1542271a31e4798f0960d35267c521fc5c263f73/lib/vcs_support/git/git_adapter.js#L14) and I expected removing/changing the flag would solve this issue.
> gitlog_analysis: ['log', '--all', '--numstat', '--date=short', **'--no-renames'**, ...

Unfortunately my limited experience with node.js has blocked attempts to determine why [this line](https://github.com/smontanari/code-forensics/blob/1542271a31e4798f0960d35267c521fc5c263f73/lib/vcs_support/git/git_adapter.js#L76) is only executed for single git repository.

**Comment by smontanari** [comment] 2017-10-23 03:08
thank you @dlehammer for the extensive report on your attempts to dig into this.

code-forensics needs to produce a git log in a particular format in order to be parseable by code-maat. the code in the module `git_adapter.js` simply wraps git commands and streams the output back to the program so it can be parsed accordingly.
In particular, the repo log/history information necessary for many of the analyses is retrieved through a `git log` command with the parameters you identified already, i.e.:

`git log --all --numstat --date=short --no-renames --pretty=format:--%h--%ad--%an`

Have you tried to manually run this command in your merged git repo? Is the output of this command different from when it's executed on a normal repository?

**Comment by dlehammer** [comment] 2018-01-04 15:54
> ```git log --all --numstat --date=short --no-renames --pretty=format='--%h--%ad--%an'```
>
> Have you tried to manually run this command in your merged git repo? Is the output of this command different from when it's executed on a normal repository?

As far as I can tell, the output format is identical between repositories and both produce output.
![git log ... diff](https://user-images.githubusercontent.com/17439718/34571282-5dc00778-f16e-11e7-83b9-fb607650713b.png)

My main suspect is still that the command isn't executed because some error blocks the earlier flow, as described in above [comment](https://github.com/smontanari/code-forensics/issues/5#issuecomment-337270537).

> When executing ```code-forensics``` on a single git repository as described in above [comment](https://github.com/smontanari/code-forensics/issues/5#issuecomment-336456797).
> The following bolded line *is* present in the log.
> 
> > ...
> > Starting 'vcs-log-dump'...
> > **Fetching git log from 2015-01-01 to 2017-10-17**
> > ...
> 
> When executing ```code-forensics``` on a merged git repository, [example](https://github.com/dlehammer/code-forensics_git_merge-repos_issue-5), the bolded line above is *omitted*!
> And instead the following bolded line is present in the log.
> 
> > ...
> > Starting 'hotspot-analysis'...
> > **Can't determine weight of collection. Assigning a value of 0 to every item.**
> > ...

**Comment by smontanari** [comment] 2018-01-05 04:15
@dlehammer I cloned your example repo and I had no problem running the hotspot-analysis
![ha-screenshot](https://user-images.githubusercontent.com/293746/34595265-ae392f92-f22a-11e7-9259-d6c657c51c11.png)

This is an extract of the output
```
[15:02:52] Using gulpfile ~/temp/merged-git_code_forensics/gulpfile.js
[15:02:52] Starting 'sloc-report'...
...
[15:02:52] Finished 'sloc-report' after 172 ms
[15:02:52] Starting 'code-stats-reports'...
[15:02:52] Finished 'code-stats-reports' after 58 μs
[15:02:52] Created: vcslog_normalised_2015-01-01_2017-10-17.log
[15:02:52] Finished 'vcs-log-dump' after 113 ms
[15:02:52] Starting 'revisions-report'...
[15:02:56] Finished 'revisions-report' after 3.84 s
[15:02:56] Starting 'hotspot-analysis'...
[15:02:56] Generating report file 2015-01-01_2017-10-17_revisions-hotspot-data.json
[15:02:56] Open the following link to see the results:
[15:02:56] http://localhost:3000/index.html?reportId=7b228da598b9213fc610a513f7be9f3e2da49fbe
[15:02:56] Finished 'hotspot-analysis' after 23 ms
```

I also checked the vcs log file produced and they look ok. Maybe you're missing something in your setup?

**Comment by dlehammer** [comment] 2018-01-08 21:27
Well, this is a bit unsettling, but I'm able to run the analysis successfully for the [example repo](https://github.com/dlehammer/code-forensics_git_merge-repos_issue-5) - just like you now.

I suspect something's changed in my environment since last time the symptom manifested itself, but I haven't taken any active steps in this regard myself - hence I'm unable to tell what's affected the outcome.

This is my current setup, as best as I can gather:
- Ubuntu 16.04.3 LTS (64-bit)
- git v2.15.1
- nodejs v4.2.6
- npm v3.5.2
- Oracle JDK v1.8.0_141-b15
- code-forensics v0.14.0

Thank you for your patience :+1:

**Comment by smontanari** [comment] 2018-01-09 04:22
No worries, I'll close the issue for now

**Closed by smontanari** 2018-01-09 04:22 UTC
