### ISSUE TITLE
Extending complexity analysis

### ISSUE THREAD

**Issue by psrijay** [smontanari/code-forensics#57] opened 2020-06-20 17:32 UTC
Hi smontanari 
Wanted to know when will you be extending complexity analysis to support other languages.Are you going to release any update in near future.Can i know how to extend it for other languages in terms of code.
 Can you provide a detailed analysis for each report generated finally i.e. for each json generated

**Comment by smontanari** [comment] 2020-07-06 11:28
@psrijay I'm open to extend the analysis to other languages as long as compatible native tools exist (or are implemented by anyone) to perform the actual complexity computation. I'm going to close this issue as a duplicate of #13, but please refer to that for context and more information. And if you have observations or more questions please add them to that issue.
In response to your other question, I have a couple of updates in my backlog that relate to two new types of analysis, but I need to find enough spare time to get that work done.

**Closed by smontanari** 2020-07-06 11:28 UTC
